### ISSUE TITLE
[1.12.2] Henhouses Have No Hardness

### ISSUE THREAD

**Issue by TheLimePixel** [setycz/ChickensMod#100]
#### Steps to reproduce (important):

1. Break a Henhouse

#### What happens:
 The Henhouse instantly breaks

#### What you expected to happen:
 The Henhouse to break after a few seconds.

____
#### Affected Versions (Do *not* use "latest"):

- Chickens: 6.0.2 (1.12.2)
- Minecraft: 1.12.2
- Forge: 14.23.0.2550

**Comment by GenDeathrow** [comment]
ok will get fixed in next update

**Comment by GenDeathrow** [comment]
Hoping to get this update out soon. Sorry for the delay. Things got crazy for me.
