### ISSUE TITLE
Chicken drops cannot be changed, let alone internal mod drops are broken

### ISSUE THREAD

**Issue by tgstyle** [setycz/ChickensMod#103]
#### Issue Description:
Seems like it is trying to register items before they are available (PreInit)?
https://gist.github.com/tgstyle/8129c2885d0d7eac809eee0bcf373217

#### Steps to reproduce (important):

1.  Change a drop

#### What happens:

No drops change

#### What you expected to happen:

Drops change
____
#### Affected Versions (Do *not* use "latest"):

- Chickens: 6.0.2
- Minecraft: 1.12.2
- Forge: 2556

**Comment by GenDeathrow** [comment]
welp.. I look into it.. I have been meaning to change how the drops are registered. I was hoping 1.12 was fixing it automatically.
