### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by tyler489** [setycz/ChickensMod#104]
Our server has a bunch of Chickens taking up ticktime. i tried using /kill @e[Type=entityChickensChicken] But it kills everyone/Everything. Any Help would be appreciated

**Comment by GenDeathrow** [comment]
Not sure what the best course of action would be. A lot of entities will cause tick time. if you have hatchery installed than /kill command wont work with them in pens.

**Comment by tyler489** [comment]
I can disable hatchery from ticking. i was wondering how to kill all Free Roaming chickens

**Comment by GenDeathrow** [comment]
its just "ChickensChicken"

**Comment by GenDeathrow** [comment]
well actually I dont normally use commands in minecraft.. but the actually command is 

`/kill @e[type=chickens:chickenschicken]`

**Comment by tyler489** [comment]
Well this kills everything. Including players /kill @e[Type=chickens:chickenschicken]  /kill @e[type=chickens:chickenschicken]

**Comment by GenDeathrow** [comment]
I just used it, and it works as intended, It only killed chicken mod chickens. I have no idea why its not working for you. But that is the correct resource ID for chickens.

**Comment by tyler489** [comment]
Blame spongeforge i guess

**Comment by GenDeathrow** [comment]
spongeforge has not played nice with chickens/hatchery since day one. and I have had others say they have had tick performance issues on sponge that forge doesn't normally get.
