### ISSUE TITLE
Question - How to get...

### ISSUE THREAD

**Issue by GSnuki** [setycz/ChickensMod#105]
As a player: how to get the redstone crystal chicken? I have not found any information about this either in JEI or in google.

**Comment by GenDeathrow** [comment]
This is the wrong mod... Right mod is >> [More Chickens](https://github.com/GenDeathrow/MoreChickens). Also its only in latest beta version, and if this is a modpack you didn't make, than it could be disabled by the developer. JEI will always show if the parents have been set. Also you didn't give version or any other information so its hard for me to really help out.
