### ISSUE TITLE
How to spawn Chickens? Command provided seems to be outdated.

### ISSUE THREAD

**Issue by ghost** [setycz/ChickensMod#106]
#### Issue Description:
Simply put: The command provided in the main pages documentation on how to spawn a custom chicken using different modifiers for Growth, Gain, Strength is incorrect, or does not provide enough information to work correctly.

Can someone test that this is working and up to date in recent versions, give some help up?

#### Steps to reproduce:

1. Use `/give @p chickens:spawn_egg 1 503 {Strength:10,Gain:10,Growth:10}` in-game.
2.  Right-click ground or block to spawn the chicken.
3. Check that the statistics reported by WAILA or similar are 10, 10, 10 in Growth, Gain and Strength (issue lies here).

#### What happens:
In my inventory, an item for spawning a chicken with the stats Growth, Gain, and Strength apparently modified with their NBT visibly different, yet when right-clicking spawning, the egg does not spawn a _modified_ Chicken with Growth, Gain and Strength to be 10, 10 and 10 each.

#### What you expected to happen:
In my inventory, an item for spawning a chicken with the stats Growth, Gain and Strength modified to be 10, 10, and 10 when you right click and spawn the chicken.

____
#### Affected Versions:

- Chickens: Chickens 4.3.2
- Minecraft: Minecraft 1.10.2
- Forge: Forge 12.18.3.2477

**Comment by GenDeathrow** [comment]
there is no longer the meta data eggs, It now uses

/give @p chickens:spawn_egg 1 {ChickenType:"chickens:coalchicken"} or something like that I dont normally use ingame commands. they use a string id in versions past 1.10.. so 1.11+. All the Id's are found in your config files. As far as the 10, 10, 10 .. I dont think you can do that with this spawn egg. you can add nbt data to all entties around ya if your using it for testing.

https://github.com/setycz/ChickensMod/blob/1.12.2/src/main/java/com/setycz/chickens/item/ItemSpawnEgg.java#L112

**Comment by ghost** [comment]
Do you know how to add NBT Data so I can 10 things?
Also, the previous command with the ID works perfectly fine in 1.10.2, don't know about yours, haven't tested.

**Comment by tyler489** [comment]
https://www.digminecraft.com/game_commands/entitydata_command.php
