### ISSUE TITLE
Please Add Stat Show Compatability for The One Probe

### ISSUE THREAD

**Issue by Dragnier** [setycz/ChickensMod#107]
#### Issue Description:
Cannot see stats in The One Probe tooltip.

#### Steps to reproduce (important):

1. Install Chickens and The One Probe
2. Use the Analyzer tool or turn the config to allow always showing stats
3. No stats show in the tooltip
...

#### What happens:
No stats show in the tooltip because there is apparently only WAILA compat.

#### What you expected to happen:
I expected to see stat is the tooltip... first mod I've seen in a long time that didn't show in The One Probe.

____
#### Affected Versions (Do *not* use "latest"):

- Chickens: 6.0.2
- Minecraft: 1.12.2
- Forge: 14.23.1.2585
-The One Probe: 1.4.19

**Comment by GenDeathrow** [comment]
Its planned for next update.

**Comment by GenDeathrow** [comment]
e95cedf559891827ae28c4f823be2cc41f251869
