### ISSUE TITLE
Breeding not working

### ISSUE THREAD

**Issue by phantom1151** [setycz/ChickensMod#108]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

#### Steps to reproduce (important):

1. add parent chicken to flint
2. cross breed parent chickens
3. new egg not given. tested over hours
...

#### What happens:
 hi i added this mod to a modpack for me and some friends. it works great other than on thing and im not sure why it will not work.

 

i added a parent chicken for every chicken that was a normal spawn so that only normal chickens would spawn in the world but i cant get them to breed and give me what they are suppose to.

 

ex: BlackChicken and GrayChicken = FlintChicken

 

Please help

 

PS: i have tried both breeding in nest and via seeds 

#### What you expected to happen:

____
#### Affected Versions (Do *not* use "latest"):

- Chickens: 4.3.2
- Minecraft: 1.10.2
- Forge: 12.18.2511

**Comment by GenDeathrow** [comment]
Have you messed with the chickens json files in the config folder?
if you have just delete them and let the files regenerate. 1.10.2v has not been touched in a long time and works fine in skyfactory. Also if you have JEI installed it should say if your have the correct chickens.  If they show nothing than your configs may have been messed up.

**Comment by phantom1151** [comment]
ok i didnt know about the json file removal part thanks for the help.

**Comment by phantom1151** [comment]
i dont see  a chickens.json in the config folder to delete just he chicken.cfg that i have edited to add parents. srry for the trouble of being an older version
  
And jei shows that it should work but its not

**Comment by GenDeathrow** [comment]
sorry json is for 1.11+ and on. Well its normally like a 20% chance or less normally. No idea why its not working, but it should be.

**Comment by phantom1151** [comment]
i looked into it using sk3 and a template and found out that it never worked in sk3 they used minetweaker for them so i just mimiced that thanks for the help
