### ISSUE TITLE
Smart Chickens spawning naturally?

### ISSUE THREAD

**Issue by brisingraerowing** [setycz/ChickensMod#113]
#### Issue Description:
Smart Chickens spawn naturally.

#### Steps to reproduce (important):

1. Make a world.
2. Fly around.
3. ...
4. Profit!
...

#### What happens:
Smart Chickens spawn

#### What you expected to happen:
Smart Chickens do not spawn naturally.

____
#### Affected Versions (Do *not* use "latest"):

- Chickens: 6.0.3
- Minecraft: 1.12.2
- Forge: 2608

**Comment by GenDeathrow** [comment]
is this a mod pack or a custom pack you made?

**Comment by brisingraerowing** [comment]
Custom pack. I don't have any spawn control mods, but it could be one of the others. With 269 mods, it may take a while to figure out which one is broken.

**Comment by GenDeathrow** [comment]
well you can look in the chicken configs.. and see if it has a spawn type on it. but smart chickens are basically regular chickens its nothing game breaking. Also sometimes you will see smart chickens if you remove a mod that had chicken support.. all those chickens switch to a smart chicken.  Even if you removed it and loaded the pack.. than added it back in later.. the chicken will already be converted to a smart chicken and stay. That only matters if those chickens were already spawned though.

**Comment by brisingraerowing** [comment]
This was a new world. I've reorganized my modlist (removed a few buggy mods and added a few not-so-buggy ones). I honestly don't care if they spawn (they look rather silly).
