### ISSUE TITLE
game crash: 

### ISSUE THREAD

**Issue by LocoMinerDad** [setycz/ChickensMod#115]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

#### Steps to reproduce (important):

1. place shredder in the world
2. trying to open gui, input feathers
3. 
...

#### What happens:
i right click with empty hand or with feathers and game crashes

#### What you expected to happen:
i expect to be able to put in feathers to make pulp

____
#### Affected Versions (Do *not* use "latest"):

- Chickens:  5.0.1
- Minecraft: 1.11.2
- Forge: 13.20.1.2579

**Comment by GenDeathrow** [comment]
Wrong Mod This is a Hatchery, Also it needs a crash log...
