### ISSUE TITLE
Server crash on boot 

### ISSUE THREAD

**Issue by Sunekaer** [setycz/ChickensMod#116]
https://github.com/jaredlll08/CraftTweaker/issues/453

#### Issue Description:
when adding recipe for chickens:spawn_egg via crafttweaker server crashes on boot
doesnt happen with client only server

#### Steps to reproduce (important):
launch a server with crafttweaker on and a recipe like `recipes.addShaped(<chickens:spawn_egg>.withTag({ChickenType: {id: "chickens:logchicken"}}), [[<ore:logWood>, <ore:logWood>, <ore:logWood>], [<ore:logWood>, <minecraft:egg>, <ore:logWood>], [<ore:logWood>, <ore:logWood>, <ore:logWood>]]);`

- Chickens: 6.0.3
- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.2.2616-universal

**Comment by GenDeathrow** [comment]
Will look at.

**Comment by DoctorFTB** [comment]
Check #120 pull request for fix Issue.

**Comment by GenDeathrow** [comment]
Thanks for changing that.. I got busy with some RL stuff. had completely forgot. And I was about to do an update soon too.  I think I may have already fixed it on my dev version.. will see.

**Comment by GenDeathrow** [comment]
Ok after about 2 days dealing with Github and issues and not be able to push anything from my computer. I should be able to get this all tested and posted soon.

**Comment by Sunekaer** [comment]
I have tested DoctorFTB´s version and it works

**Comment by GenDeathrow** [comment]
Hopefully fixed on latest version
