### ISSUE TITLE
[1.12.2] The return of Feathergeddon - Baby Chickens spewing feathers!

### ISSUE THREAD

**Issue by MokahTGS** [setycz/ChickensMod#117]
#### Issue Description:
Hatching a baby chicken causes them to spew feathers at an insane rate leading to feathers everywhere.  This bug has happened before and gone away on it's own leading me to suspect a mod interaction gone wrong.

#### Steps to reproduce (important):

1. Hatch baby chicken
2. Watch Feathers spawn like mad. 
3. Scratch head and setup void pipes...
...

There have been many reports of this and it would be helpful if someone knew where the old issue where, to see if there is a correlation.  Would love to know if others have seen this.  This issue was not there in previous versions of our mod collections (not a public pack) but just started recently.  Big things that for some reason my gut tells me might be involved:  We added Buildcraft, which is what we had in 1.10 when we last saw this issue.  This is just my gut theory, so, no real evidence.  I will do some testing and report back.
____
#### Affected Versions (Do *not* use "latest"):

- Chickens: 6.0.3
- More Chickens: 3.1.0
- Hatchery: 2.1.2
- Roost: 1.2.0
- Minecraft: 1.12.2
- Forge: 2611

**Comment by MokahTGS** [comment]
Initial testing of removing buildcraft:  Newly hatched baby chickens did not spew feathers when Buildcraft was not present.  Putting Buildcraft back into the mix caused then newly hatched baby chickens to spew feathers.

EDIT:  Never mind:  Baby chickens are still spewing feathers even when Buildcraft is disabled.  No idea why this is happening.

**Comment by MokahTGS** [comment]
More Testing:  Using the color eggs and throwing them to get a baby chicken produces a baby chicken that does not spew feathers.

Using the Hatchery nest to hatch a chicken produces a baby chicken that does not spew feathers.

Both of the above chickens are Lapis Blue Chickens with the 1,1,1 stats.  Bread chickens  hatched in the nests with stats or other chickens seem to hatch spewing feathers however.

Taking eggs with stats (10,10,10) and throwing them produces a baby chicken that spews feathers.

**Comment by GenDeathrow** [comment]
how fast do they spew feathers.. at what rate?

**Comment by MokahTGS** [comment]
Very fast... They are pouring out. We have an advanced item collector setup and a trash can but if we have multie babies it will overload the system

**Comment by tyler489** [comment]
#89 

Is botania installed?

**Comment by tyler489** [comment]
Or quark

**Comment by tyler489** [comment]
https://github.com/timrwood/roost/blob/5db487ae5c0cc54e78ef7246c45ac570f0bb6901/src/main/java/com/timwoodcreates/roost/data/DataChickenVanilla.java
Botania and quark also add chickena drop feathers
 ```@Override
	public ItemStack createDropStack() {
		Item item = rand.nextInt(3) > 0 ? Items.EGG : Items.FEATHER;
		return new ItemStack(item, 1);```

**Comment by MokahTGS** [comment]
Both botania and quark have that option turned off.   Always have.

**Comment by MokahTGS** [comment]
Actually botania removed that from the 1.12.2 version a long time ago.

**Comment by MokahTGS** [comment]
This might be preliminary, but Terraqueous has an option for feather drops from chickens that we turned off.  Feathers seem to have stopped spewing.  I'm reporting this to them to see if they have something in their code that is causing issues.

**Comment by GenDeathrow** [comment]
Hope maybe we can narrow it down with this. @MokahTGS Thanks for doing some heavy testing with this.

**Comment by MokahTGS** [comment]
We have been running all night with no feather spewing.   This might be it.   It would be nice if someone else could confirm this with another setup.
