### ISSUE TITLE
Enderio intergration

### ISSUE THREAD

**Issue by tyler489** [setycz/ChickensMod#118]
I was talking to enderio devs about chickens mod chicken not spawning in spawners. They said they could 
Do it then they looked into it and they said they couldnt because the following code is invalid in 1.12 ```@Mod(modid = ChickensMod.MODID, name = ChickensMod.NAME, version = ChickensMod.VERSION, acceptedMinecraftVersions = "[1.12, 1.12.2]", dependencies = "required-after:forge@[14.21.1.2387,);")
@EventBusSubscriber
public class ChickensMod {
	public static final String MODID = "chickens";
	public static final String VERSION = "@VERSION@";
	public static final String CHICKEN = "ChickensChicken";
	public static final String NAME = "Chickens";
        public static final Logger log = LogManager.getLogger(MODID);```

**Comment by GenDeathrow** [comment]
Was this conversation on github? got a link?

**Comment by tyler489** [comment]
On there discord http://discord.gg/sgYk3Jr

**Comment by tyler489** [comment]
Also would it be possible to do somethink like this ````but you may suggest to GenDeathrow to split the entity into multiples, e.g. "chicken1" for sum(data) 0 to 10, "chicken2" for 11-20, ... that would make it easy for all mods that have spawning to configure different cost without having to add special cucken code````

**Comment by GenDeathrow** [comment]
hopefully should be fixed on latest version
