### ISSUE TITLE
Water egg turns into black ink baby

### ISSUE THREAD

**Issue by Dragonracer73** [setycz/ChickensMod#126]
#### Issue Description:
Testing out a new modpack for The Leauge of Ordinary Gamers titled coop life 2. Using version 6.1.0 of the chickens mod,and also have More chickens (ver. 3.2.0) installed. When attempting to hatch a water chicken, a black ink baby appears, after the time limit is up.

#### Steps to reproduce (important):

1. followed recipe for water chicken egg
2. placed egg in nest
3. black ink baby appears after time limit
4. having op on server I also attempted to grab one from jei, with the same result

#### What you expected to happen:

should have gotten a water chicken baby
____
#### Affected Versions (Do *not* use "latest"):

- Chickens: 6.1.0
- Minecraft: 12.2
- Forge: 14.23.3.2660

**Comment by FoxBotGames** [comment]
Referenced from Git of modpack relating to this issue

**Comment by Dragonracer73** [comment]
after further study, (and 6 tries) it appears this is not a bug, water eggs, and water CHICKEN eggs, come from the snowball gunpowder breeding
