### ISSUE TITLE
Game immediately crashes upon loading in a custom modpack of mine

### ISSUE THREAD

**Issue by hellfireBeah** [setycz/ChickensMod#130]
#### Steps to reproduce (important):

1. Attempt to load game
2.  Game crashes upon loading
Text log
---- Minecraft Crash Report ----

https://pastebin.com/fwYdpBgf

#### What happens:
The game crashes

#### What you expected to happen:
To load

____
#### Affected Versions (Do *not* use "latest"):

- Chickens: 6.1.0
- Minecraft: 1.12.2
- Forge: 14.23.4.2707

**Comment by hellfireBeah** [comment]
Note the modpack was working before i added chickens

**Comment by GenDeathrow** [comment]
Well it just means there are too blocks being registered. I have read that chisel could be taking up a lot of block id's, but chickens isn't the issue. It just apparently the last straw. Its not so much this mod as just too many mods registering blocks. And chickens only registers 6 or so. There is still a max of 4096 ids. 

There is a mod called ["Not Enough Ids"](https://minecraft.curseforge.com/projects/notenoughids) I have never used it, but it may work for what you need. 

Also remember unless its changed in 1.12 old worlds keep ids even if you uninstall a mod.
