### ISSUE TITLE
Kinda of a weird problem

### ISSUE THREAD

**Issue by ghost** [setycz/ChickensMod#137]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

#### Steps to reproduce (important):

1. Launch Modpack Beyond the Void 2
2. Log into Multiplayer and start an island in plains biome
3.  Notice no chickens will spawn at there default value in the config
...

#### What happens:
When we updated to a new version of Forge it seems like the chickens might have stopped spawning, we don't know if it something we did or forge as we had to update forge cause of a few mods in our pack using new forge versions.

#### What you expected to happen:
Away to maybe tell us why this is happening or if this can be fixed in somewhere as we are lost on what's causing it.

____
#### Affected Versions (Do *not* use "latest"):

- Chickens: 6.1.0v (MC 1.12.2)
- Minecraft: 1.12.2
- Forge: 1.12.2 (modded) forge-14.23.5.2776 but seems its happening above that version as well

**Comment by TacticalUniverse** [comment]
@GenDeathrow could you help me?
