### ISSUE TITLE
What are the chickens ids?

### ISSUE THREAD

**Issue by Dolphin2Point1** [setycz/ChickensMod#148]
I am trying to use craft tweaker to tweak the chickens recipes, but the chicken eggs are null.
Log chicken is supposed to be: <chickens:spawn_egg:108>
Flint chicken is supposed to be: <chickens:spawn_egg:101>
and Sand Chicken is supposed to be: <chickens:spawn_egg:105>
but none of them seem to be working.
I am using 6.0.4v, and I hope you can get to me.

**Comment by GenDeathrow** [comment]
Egg id were removed quite some time back. It now uses nbt data for eggs.. Except for they dye chickens. They are the only ones that still uses meta data.  I would suggest using craft tweaker or mputils to get the nbtdata to see ID's.

Edit.. once you know the nbt data you need.. all the chicken id's can be found in your chickens.json in the config file.

**Comment by Dolphin2Point1** [comment]
I was thinking it was nbt.
