### ISSUE TITLE
Breeding Problem

### ISSUE THREAD

**Issue by DasHeinzchen** [setycz/ChickensMod#151]
I have a problem:

I tried to breed a Iron Chicken from a Flint Chicken (10/10/10) and a Bone White Chicken (10/10/10).

But the Iron Chicken is only 1/1/1. Could someone help me, please?

- Chickens: 6.1.0
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.2.2611

**Comment by GenDeathrow** [comment]
That was changed along time ago. Now only chickens of the same type get the better stats. New chickens mutations get lower stats. I couldn't tell ya when that change but it was a very long time ago. I believe it was right before I took over the mod.

**Comment by DasHeinzchen** [comment]
Oh, I didn't knew.
P.S. Your mod is really nice.

**Comment by GenDeathrow** [comment]
np, glad you enjoy it.
