### ISSUE TITLE
Game Crashing when Placing egg in nest

### ISSUE THREAD

**Issue by 00creeper** [setycz/ChickensMod#154]
#### Issue Description:
I installed this mod along with the more chickens mod and the hatchery mod. When I started to get into the mod I found a bug that made it not usable. I placed down a hatchery nest and then placed a nether quartz chicken egg into it and then it crashed my game. I am not sure exactly which of these three mods caused this issue but i thought I would start here.

#### Steps to reproduce (important):

1. Place down nest from hatchery mod
2. Place egg into it
3. 
...

#### What happens:
The game crashes upon the completion of these two steps.

#### What you expected to happen:
I expect the egg to eventually grow into a baby chicken

____
#### Affected Versions (Do *not* use "latest"):

- Chickens: 6.1.0
- Minecraft: 1.12.2
- Forge: 14.23.5.2779
- More Chickens: 3.1.0
-Hatchery: 2.0.0
[crash-2019-05-12_15.46.10-client.txt](https://github.com/setycz/ChickensMod/files/3170509/crash-2019-05-12_15.46.10-client.txt)

**Comment by GenDeathrow** [comment]
Its actually a hatchery issue. I look into it.. Have you tried updating your forge version.. or use the recommended?

**Comment by 00creeper** [comment]
I switched to the newest version of hatchery and it seemed to fix the problem. Thanks for your help!
