### ISSUE TITLE
log chickens don't spawn in skyfactory 4 

### ISSUE THREAD

**Issue by Lordcopenhagen0** [setycz/ChickensMod#170]
I'm using the 12.1 version of the chickens mod and the only chickens spawning are the roosters cant find log sand or flint how do i make it work with skyfactory 4. Is their a setting in the config to fix it? any help would be great. other then tis issue the mod is amazing.

- Chickens: 
- Minecraft: 
- Forge:

**Comment by GenDeathrow** [comment]
That would a skyfactory 4 question. As mod developers can change the rules.
