### ISSUE TITLE
DNA

### ISSUE THREAD

**Issue by setycz** [setycz/ChickensMod#18]
So each chicken is unique and has different properties and breeding is more fun.

**Comment by setycz** [comment]
* Growth= the speed of which the chicken grows
* Gain = the amount of produce the chicken will 'create'
* Strength = the ability for a chicken to carry it's stats over to the children chickens

**Comment by hron84** [comment]
Idea: Check AgriCraft tooling for planning the actual gameplay mechanics. Analyzer for eggs, maybe integrating with waila/TheOneProbe for showing stats on the chicken in tooltip, some tool to pick up a chicken and analyze it.

**Comment by setycz** [comment]
@hron84 Hi, thank you for your idea. In fact, I really like AgriCraft and its game mechanics and I will think about some kind of analyser, that could be really fun!

**Comment by GenDeathrow** [comment]
Just so you know this new mechanic rocks

**Comment by setycz** [comment]
Thank you!
