### ISSUE TITLE
 chickens-1.9-1.3 crashes dedicated forge server 1.9 build 1809 on startup

### ISSUE THREAD

**Issue by kreezxil** [setycz/ChickensMod#25]
I guess you should update your mod description to say this isn't server capable. But it sure would be sweet if it was.

Issue: chickens-1.9-1.3 crashes dedicated forge server 1.9 build 1809 on startup

crash report:
https://gist.github.com/250dd8f4919e1c30ef3f

fml server latest:
https://gist.github.com/aca89ea854194254e616

**Comment by setycz** [comment]
Hi, Server support is implemented and was tested with forge 12.16.0.1805. It might have something to do with forge, version 1.9 is still pretty unstable. I'll check the mod with it and let you know.

**Comment by setycz** [comment]
The issue was replicated and fixed. The problem was with the build, seem I should stop coding at night. New version 1.3.1 should work well.

**Comment by setycz** [comment]
Many thanks for the feedback ;). Please, let me know if you find any other issue.
