### ISSUE TITLE
1.9-2.0 crashes dedicated forge server 1.9 build 1821 on startup

### ISSUE THREAD

**Issue by kreezxil** [setycz/ChickensMod#28]
Issue: chickens-1.9-2.0 crashes dedicated forge server 1.9 build 1821 on startup

crash report:
https://gist.github.com/96eae6899f93a29c4e13a2ab9c674750

fml server latest:
https://gist.github.com/3052fc548570578b6ccff0b7dba4ce3b

**Comment by setycz** [comment]
Chickens works with 1805 so it seems they changes API in the new Forge. I'll update Chickens to 1821. I'll inform you when the updates is available.

**Comment by setycz** [comment]
jei_1.9:3.1.0.170 doesn't work either, I will try to update to jei_1.9-3.1.2.172.

**Comment by setycz** [comment]
fixed in 2f3d24c4d65cf2c24c59980f416a8cb6634cf708 . JEI doesn't support 1821 yet. Consider using older release.
