### ISSUE TITLE
1.9-2.0.2 crashes dedicated forge server 1.9 build 1863 on startup

### ISSUE THREAD

**Issue by kreezxil** [setycz/ChickensMod#29]
Issue: chickens-1.9-2.0.2 crashes dedicated forge server 1.9 build 1863 on startup

crash report:
https://gist.github.com/9f32239eb54fb94847ccd768407adfe2

fml server latest:
https://gist.github.com/892b5f43dc6de037fd76bfca31e69c41

**Comment by setycz** [comment]
Forge API changed. I've updated to the newest forge.
