### ISSUE TITLE
Custom Chickens?

### ISSUE THREAD

**Issue by Darkosto** [setycz/ChickensMod#34]
Is there a possibility of allowing Custom Chicken additions? Maybe the assets for the custom chicken can be taken from the blocks/items it drops?

Thanks for a great mod! I'm looking forward to using it in SkyFactory :D
Darkosto

**Comment by setycz** [comment]
Hello Darkosto. Thanks for your great feedback! You cannot imagine what is means for me! ;) The think is that I was quite busy now, but your message gives me energy to get back to modding :D. I'll try to investigate what are the possibilities and I will let you know. 

Once again, thank you for the feedback!
Jakub

**Comment by GenDeathrow** [comment]
@setycz  you could prolly close this, It was added before more chickens.  This post is what started the "More Chickens" mods.
