### ISSUE TITLE
Fix version number in the mod annottations

### ISSUE THREAD

**Issue by setycz** [setycz/ChickensMod#41]
From #40:
> Also Version numbers are incorrect for the @Mod annotation. Last time I checked I think you added - "MCVersion - ModVersion". More chickens is dependent on Chickens mod, but I cant make sure its dependent on a specific version because of the dash" The Version number should be just the ModVersion only with no letters or special characters. basically "1.0.0" or "1.0".

**Comment by GenDeathrow** [comment]
Thank you.
