### ISSUE TITLE
Analyser for chickens

### ISSUE THREAD

**Issue by setycz** [setycz/ChickensMod#51]
Similar to AgriCraft, unknown properties first and some tool to analyse them.

**Comment by GenDeathrow** [comment]
I'm going to have to figure out a mechanic to for hatchery eggs. They now show the stats in the egg tool-tip. not sure if I should just keep it as is.. or figure out something to analyse it.

**Comment by setycz** [comment]
Yeah, I was wondering about it as well. Maybe so block form would be useful. I am going to make analyzer configurable, so it can be disabled if it would cause any problems.
