### ISSUE TITLE
Request for properly registered spawn eggs

### ISSUE THREAD

**Issue by vadis365** [setycz/ChickensMod#52]
Please ignore this if the changes have already been implemented.
Would it be possible for you to register your spawn eggs using the vanilla/forge standards rather than using metadata? I have a mod that allows creation of mob spawn eggs in survival worlds and have had to add a special case to support your mod. Although this isn't an issue really as the support has already been added it would honestly be better.

*Edit mod repo for reference: https://github.com/vadis365/Mob-Grinding-Utils

**Comment by setycz** [comment]
Hi @vadis365 , thank you for your feedback. I'll definitely check it, my spawn eggs were originally written for 1.8.x Minecraft so I am sure that many things changed since the time.

**Comment by setycz** [comment]
@vadis365 I briefly went through the vanilla spawn egg implementation (ItemMonsterPlacer) and it uses EntityList registry. The problem with EntityList registry is that you can have only single entry per entity ID. My chickens share the same ID so they can mate together and make breeding possible, the chicken type is determined by NBT data (it's similar to horses implementation). That means that I can only create a single vanilla spawn egg which can e.g. spawn a random chicken (as the horse spawn egg does) and that's not what I wanted. Would it be helpful for you? Do you have any suggestions? I would appreciate your opinion.
