### ISSUE TITLE
EnderIO Tank Overflow

### ISSUE THREAD

**Issue by voidedWarranties** [setycz/ChickensMod#55]
#### Issue Description:
The tank overflowed

#### Steps to reproduce (important):

1. Get a Lava Egg (not a Lava Chicken Egg)
2. Get a EnderIO Tank
3. Right Click the Egg on the Tank

#### What happens:
The tank "overflows"
![2016-12-29_10 39 23](https://cloud.githubusercontent.com/assets/14946719/21552284/5f88863a-cdb5-11e6-898f-4f84ecfc925e.png)

#### What you expected to happen:
Absolutely Nothing
____
#### Affected Versions (Do *not* use "latest"):

- Chickens: chickens-4.1.1 (or latest) LUL
- Minecraft: 1.10.2
- Forge: 2185

**Comment by tgstyle** [comment]
HenryLoenwind did a good explination here.

https://github.com/SleepyTrousers/EnderIO/issues/3954#issuecomment-269769783

**Comment by tgstyle** [comment]
EnderIO added protections for this, it doesn't fix the issue in Chickens though.

https://github.com/SleepyTrousers/EnderCore/commit/814629ff0fe62d0784b3d2ab20268ffce300c80a

**Comment by setycz** [comment]
I'll investigate that, thank you.
