### ISSUE TITLE
I would like to see how can I spawn color chickens

### ISSUE THREAD

**Issue by setycz** [setycz/ChickensMod#59]
Add another JEI tab which can show that throwing an egg has a chance to spawn the chicken.

**Comment by ghost** [comment]
I want it cause i can't seem to get chicken spawns

**Comment by JaRyCu** [comment]
@setycz You get the colored eggs by dying eggs and then throwing them.  So far I've gotten blue chickens, red chickens, and a black chicken.  When I did the white chicken (bone meal + an egg), the resulting chickens look like skeleton chickens but they don't burn in the sun.  I did this in the most recent episode of my LP on the Unstoppable modpack last night if you're interested: https://www.youtube.com/watch?v=R0E_DFJtroQ
