### ISSUE TITLE
Eggs don't break in dispenser

### ISSUE THREAD

**Issue by Homarus** [setycz/ChickensMod#61]
#### Issue Description:
If you use a dispenser to break eggs, the egg don't break. Vanilla eggs will.
The fire power is not the same as vanilla eggs.

(found in skyfactory 3, but also tested only with forge and ChickensMod)

- Chickens: 4.2.2
- Minecraft: 1.10.2
- Forge: 12.18.3.2202

**Comment by setycz** [comment]
Thank you for the report. I've fixed that and it will be released in the next version.

**Comment by Homarus** [comment]
Question, I use the mod "hatchery" to get drops from the chickens. You get also a lot of eggs, but the don't work in a dispenser. Waila tells me that the Eggs are from the mod "Hatchery". In JEI I only find Chickensmod eggs. What mod dev do I need to ask for this? Chickensmod, MoreChickens or Hatchery?

**Comment by GenDeathrow** [comment]
That would be me..  My Hatchery eggs are different from Setycz Eggs.  https://github.com/GenDeathrow/Hatchery/issues

**Comment by setycz** [comment]
@GenDeathrow thanks. @Homarus please use Hatchery issue tracker, Thank you
