### ISSUE TITLE
Failed crossbreeding gives eggs with inflated stats

### ISSUE THREAD

**Issue by Quetzi** [setycz/ChickensMod#63]
Not sure whether or not this is by designor a bug, but it's very easy to circumvent the whole process of having to breed your chickens up to high stat levels. If you breed a chicken with 1 1 1 stats with a chicken with 10 10 10 stats then the eggs will usually have stats of 8s and 9s, even if no crossbreed is possible. I would expect egg stats to be produced somewhere in the middle ground, so stats closer to 5s and 6s.

**Comment by setycz** [comment]
Yeah, I didn't want to be it boring but it's true that it could be more challenging. Thank you for the suggestion.

**Comment by GenDeathrow** [comment]
I dont think it will be boring if you increase the challenge a bit more. From what I can tell alot of ppl just get the dye chickens to 10-10-10 and than move up. resualting in high stat chickens forever. 

Personally I think you can decrese the chickens of the same type some for more challenge, but on a successful crossbreeding I think chickens should always start near 1-1-1. Or maybe 3-3-3 if parents had high str.
