### ISSUE TITLE
Chickens are giving Resources every 2 seconds

### ISSUE THREAD

**Issue by Darkosto** [setycz/ChickensMod#69]
#### Issue Description:
I just updated to the latest version, and my Log and Nether Quartz chickens are dropping resources every 2 seconds, instead of minutes.

#### Steps to reproduce (important):

1. Update to latest version: 4.3.1
2. Watch chickens drop resources too quickly
3. 
...

#### What you expected to happen:

____
#### Affected Versions (Do *not* use "latest"):

- Chickens: 4.3.1
- Minecraft: 1.10.2
- Forge: 2209

**Comment by setycz** [comment]
My local changes went to the release :D . Sorry for inconvenience, 4.3.2 version with fix released now

**Comment by Darkosto** [comment]
Hahaha, I was confused for a second on why I was getting so much Nether Quartz :P 

Thanks for the update :)
