### ISSUE TITLE
hen house does nothing

### ISSUE THREAD

**Issue by suneyedset** [setycz/ChickensMod#71]
I am trying to use the Hen House, but nothing happens. Put a hay bale in the hen house, still nothing. Chickens are around the hen house, chickens are also laying eggs and pooping. The hen house collects nothing. There are many slots in the hen house when the gui is opened. I have tried putting the hey bale in various slots. Is there some place I can go and find out more about the Hen house and how it is used? I have looked for videos, but the only ones I've found just have some goofball running around spawning chickens in creative mode, and not a whole lot else. How does the Hen house work?

**Comment by GenDeathrow** [comment]
Place haybales in.

 if its vanilla chickens you have to give them a book to teach them to use the hen house.  If im not mistaken they need line of site and in the middle pen you made. They wont pick up manure yet.

**Comment by setycz** [comment]
Precisely as @GenDeathrow mentioned (thank you)! Place the henhouse in the middle of your farm (the range is 4 block on each side), put some vanilla haybale blocks into the top left slot and that's it. However, it works with Chicken's chickens only and not vanilla one. Vanilla chicken can be turned into the modded one by using a book on it  ;]. Please let me know if it works for you.
