### ISSUE TITLE
Chickens vanish from breeding pens

### ISSUE THREAD

**Issue by railstar0083** [setycz/ChickensMod#72]
#### Issue Description:
Modpack: Skyfactory 3

Issue:  Chickens in nesting boxes all vanished.  Free roaming chickens did not.  The boxes were then bugged and would not accept new chickens until broken and replaced.

#### Steps to reproduce (important):

I am re-breeding and replacing chickens to see if the same thing happens after my next logout.

#### Affected Versions (Do *not* use "latest"):

- Chickens: 4.2.2
- Minecraft: 1.10
- Forge:  Not sure.

**Comment by GenDeathrow** [comment]
This is not his mod.. the nesting pens belongs to my mod. Hatchery please close this and add it to hatchery not chickens.

**Comment by GenDeathrow** [comment]
https://github.com/GenDeathrow/Hatchery/issues/42

**Comment by GenDeathrow** [comment]
https://github.com/GenDeathrow/Hatchery/issues/46

**Comment by railstar0083** [comment]
Sorry about the confusion!
