### ISSUE TITLE
Baby Chickens Drops Feathers Continually

### ISSUE THREAD

**Issue by MokahTGS** [setycz/ChickensMod#79]
- Chickens: 4.3.2
- More Chickens 1.0.11
- Hatchery 0.2.10
- Animania 1.0.4.6
- Quark 1.1-70 (Feather drops disabled in config)
- Minecraft: 1.10.2
- Forge: 2254

Baby Chickens are dropping feathers continually like a fountain of feathers.  Once they become adults the feather dropping returns to normal.

This only happens with baby chickens that are grown in the Hatchery nest. so I don't know if this is a Hatchery issue or just chickens.

**Comment by Puremin0rez** [comment]
I'm getting this same problem on my large modpack - has anyone tested to see if this is isolated to the mod or a result of a combination of mods?

**Comment by GenDeathrow** [comment]
This isn't a Chickens mod issue,As Chickens doesn't add feathers to drops. Hatchery does drop eggs but this doesn't seem like a Hatchery issue. but Im currently looking at Hatchey's code and I have check before feathers are called to drop to check for isChild. If it was Hatchery than you'd get manure just like the feathers. It sounds like another mod is interacting that adds feather drops, since I cant tell which one it is.

**Comment by Puremin0rez** [comment]
I thought it may be Quark since they do make some changes to chickens and feathers, but after disabling that I still didn't see a change. For now... players are building voiding setups for the excess feathers lol

**Comment by GenDeathrow** [comment]
ill check quarks code and do some testing on my end. but with just hatchery and chickens I dont get the foutain of feathers in my dev enviroment.  but for Chickens sake close this issue. IIve had some one report in hatchery on this before I can reopen it.. check in closed issues for now

**Comment by MokahTGS** [comment]
OK, the only other mod that I think might be involved is Animania as it replaces the default chickens in the game.  Not sure it does anything with drops however as drops are managed in nests.

**Comment by MokahTGS** [comment]
So after deactivating Animania the problem still persists, so it's not an interaction with that mod that's causing this.

**Comment by GenDeathrow** [comment]
https://github.com/GenDeathrow/Hatchery/issues/75 << to here

**Comment by GenDeathrow** [comment]
@MokahTGS Pls close this issue, its not a chickens issue.
