### ISSUE TITLE
[Request] Breeding Iron Chicken and Quartz Chicken produces "Quartz Enriched Iron" chicken, when Refined Storage mod is present.

### ISSUE THREAD

**Issue by JaSpr** [setycz/ChickensMod#80]
"Quartz Enriched Iron" is an integral part of Refined Storage.  Currently I'm collecting all the iron and quartz that I'm getting from those respective chickens and crafting the QEI manually, but it'd be nice to have a chicken of that type when both mods are present, as they are in FTB SkyFactory 3.

**Comment by GenDeathrow** [comment]
>> meant more for more chickens mod
