### ISSUE TITLE
Inverted textures enderio chickens

### ISSUE THREAD

**Issue by hedevil4** [setycz/ChickensMod#84]
#### Issue Description:
I play on skyfactory3 (release 3.0.10) and textures of vibrant alloy chicken and energetic alloy chicken are inverted!

**Comment by GenDeathrow** [comment]
It's been fixed on the latest build, but sf3 will probably not get another update. Just just update manually.  Also this is not the correct mod.. it's the "More Chickens" add-on.

**Comment by GenDeathrow** [comment]
Please close this since it's not the correct mod.

**Comment by hedevil4** [comment]
ok sorry and thank's!
