### ISSUE TITLE
[Suggestion] increased spawn chance from eggs

### ISSUE THREAD

**Issue by UpcraftLP** [setycz/ChickensMod#85]
as the title says I'd like to have an increased chance of spawning a new chicken when throwing eggs, as the current chance is way too low for the rate at which the chickens produce eggs

version: 5.0.0
MC version: 1.11.2
Forge: 13.20.0.2315

**Comment by GenDeathrow** [comment]
This is the same as vanilla, but if you ever noticed sometimes you get more than one chicken from one egg.

**Comment by UpcraftLP** [comment]
Yeah I noticed, but that doesn't make sense to me...

**Comment by ghost** [comment]
Try the [Hatchery](https://minecraft.curseforge.com/projects/hatchery) nest, 100% success.
