### ISSUE TITLE
[BUG] thrown egg entity shows vanilla egg texture

### ISSUE THREAD

**Issue by UpcraftLP** [setycz/ChickensMod#86]
#### Steps to reproduce:
throw any colored egg

#### What happens:
the entity renders the texture of the vanilla chicken egg

- Chickens: 5.0.0
- Minecraft: 1.11.2
- Forge: 13.20.0.2315

**Comment by EPIICTHUNDERCAT** [comment]
im thinking this was a "lazy" way of doing it maybe ? xD

**Comment by UpcraftLP** [comment]
probably, yeah, but changing the color is as easy as adding a single call to `GLStateManager.color()` to the Renderer class...

**Comment by GenDeathrow** [comment]
Its been meaning to get fixed, but hasn't been high on the list of things to get changed.

**Comment by GenDeathrow** [comment]
Getting fixed next update.. 1.12, I look into backporting later.

**Comment by GenDeathrow** [comment]
https://github.com/setycz/ChickensMod/commit/ba5e0ae9204c3fda6b202858ac7e8fbdd66232dd

**Comment by Dragnier** [comment]
In 1.12.2, I can throw any mod eggs and they only spawn vanilla chickens. Since I always use nests to hatch eggs I want to keep, I only found this because I was getting rid of extra eggs.

**Comment by GenDeathrow** [comment]
Are they ChickensMod eggs or Hatchery Mod Eggs? Also this issue isn't the same as the one your referring too, it be best to make a new issue.
