### ISSUE TITLE
[BUG] Henhouse GUI output slot accepts items

### ISSUE THREAD

**Issue by UpcraftLP** [setycz/ChickensMod#87]
You can insert items into the output slot of the henhouse GUI.

This is not a game-breaking bug, but somewhat easy to fix. ;D

- Chickens: 5.0.0
- Minecraft: 1.11.2
- Forge: 13.20.0.2315

**Comment by niftybottle** [comment]
This lets you select which items it will collect if you have more that nine types though.

**Comment by GenDeathrow** [comment]
A lot of the GUI bugs will be fixed in next 1.11.2 update
