### ISSUE TITLE
Inkompatible with Galacticraft

### ISSUE THREAD

**Issue by Darianna77** [setycz/ChickensMod#88]
I use Chickens in a customized Pack with Galacticraft because i love your mod and it is a great addition for my gameplay. But when i try to start the Game it crashes whilst its initialize. I know there are many other mods in the pack but When i disable Chickens...it starts....also when i disable Galacticraft...so it must be an inkompatibility between these two mods.
Galacticraft was a new addition have played the pack before with Chickens...Hatchery and More Chickens without Problems

____
#### Affected Versions (Do *not* use "latest"):

- Chickens: 4.3.2
- Minecraft: 1.10.2
- Forge: 12.18.3.2316

[https://pastebin.com/ixph84as](url)

**Comment by GenDeathrow** [comment]
The only problem is the crash doesn't point at any particular issue.  This is a model baking issue. Chickens doesn't really have many models, and they all use the json models, where as galactic craft has many. I have no idea why it would be crashing out with chickens. Have you tested this with just Chickens & Galacticraft? and can you load each on individually?

**Comment by bogger33** [comment]
galacticraft also has a ton of ridiculously huge textures, it's probably a galacticraft problem.

You can check with https://github.com/mezz/TextureDump/releases
