### ISSUE TITLE
Chicks overgenerate feathers by a preposterous amount

### ISSUE THREAD

**Issue by katubug** [setycz/ChickensMod#89]
#### Issue Description:
I'm running a custom modpack on 1.10.2 with this, More Chickens (1.1.6), and Hatchery (0.2.10) (and [115 other mods, formerly including ChickenShed](https://docs.google.com/spreadsheets/d/1IE5UIXzZb9tPynBqVBrvbcifH-RAABIzYKVfdhfIglI/edit#gid=0)). After I began amassing my chicken army - I mean uh, my darling livestock, I began to notice a rather overabundance of feathers. It got worse as I went along, and eventually I figured out that it was tied to the chicks. During their chickhood, they produce feathers at a blistering pace.

I thought ChickenShed was the culprit, so I messed with it for a long time, eventually removing it entirely. Now, playing without it, the problem remains. I have 15,000 feathers and I doubt I will ever use them all. I don't know what's going on or how to stop it. Please let me know what other information you might need!

#### Steps to reproduce (important):

1. Breed chickens OR
2. Hatch an egg
3. The resulting chick should be a prolific fount of feathers
...

#### What happens:
![2017-07-08_23 26 12](https://user-images.githubusercontent.com/20935286/27991269-9c2b164e-6436-11e7-8d25-a20d885e009a.png)

#### What you expected to happen:
Not this.

____
#### Affected Versions (Do *not* use "latest"):

- Chickens: 4.3.2
- Minecraft: 1.10.2
- Forge: 12.18.3.2297

**Comment by katubug** [comment]
Upon further inspection, I'm not 100% certain that it's JUST the chicks. It's insane though...

**Comment by GenDeathrow** [comment]
Others have reported this in my mod hatchery Seems to happen when the eggs hatch, but we haven't figured out whats causing it.  are you running sponge at all? . but lets move this over here
https://github.com/GenDeathrow/Hatchery/issues

**Comment by GenDeathrow** [comment]
also the only thing that gives feathers in hatchery are chickens in pens.. chickens mod doesn't give feathers at all. so Im not sure whats causing this.

**Comment by katubug** [comment]
I'm not familiar with anything called sponge, so probably not. They are definitely not in the pens when they're spewing feathers, since usually it's the chicks, as I mentioned. Thanks for the response, do I need to repost or is the thread migrated automatically?

I'll try to do some testing in singleplayer and see if I can isolate the problem.

**Comment by GenDeathrow** [comment]
here https://github.com/GenDeathrow/Hatchery/issues/75

**Comment by tyler489** [comment]
#117
