### ISSUE TITLE
[Request] Egg neutralization

### ISSUE THREAD

**Issue by ghost** [setycz/ChickensMod#90]
I'd like a way to convert ChickensMod eggs back to vanilla for storing the excess. (Especially when you have stacks of 1 or 2 log chicken eggs in various stages of evolution.)

**Comment by ghost** [comment]
Maybe an egg-washing hopper?

**Comment by GoghGirl** [comment]
You can compost them into dirt! Just use a transfer pipe to move them into a wodden barrel.. And then wooden barrel into a chest of dirt and you are set for dirt forever!

**Comment by ghost** [comment]
Works, and is useful with sky block maps, but not all packs have the necessary mods (which I always misspell). Besides, once you have a 10/10/10 of every chicken and extras of ones you need more of, the fertilizer quickly becomes an issue and can be composted just as easily. I can turn them into food with Cook the Eggs!, but I've got to do it one or two eggs at a time because of the metadata. Plus, Cooking for Blockheads doesn't seem to recognize them as eggs.

**Comment by GenDeathrow** [comment]
I think your talking about Hatchery eggs, that store a "Chickens Mod" chicken in it. This isn't a bad idea for Hatchery, but doesn't really involve Chickens Mod.
