### ISSUE TITLE
[Request] Animania Integration

### ISSUE THREAD

**Issue by drinfernoo** [setycz/ChickensMod#91]
I'm not sure if this planned or really even possible, but Animania integration could be really neat with this mod. Their chicken breeding mechanics lend themselves to a much more realistic farming experience, and it would be really neat if this mod and that one played nice with each other ;)

**Comment by GenDeathrow** [comment]
These mods are go into two completely different directions. Animania is meant to have a more realistic feel, where chickens is kinda far from realistic.  I can say that I don't think ,we will add integration like that. Its a good idea, but I think it would be better to have someone make a addon to do this instead.

**Comment by drinfernoo** [comment]
Fair enough. When this mod updates to 1.11.2, will they coexist without causing problems?

**Comment by GenDeathrow** [comment]
Do they not atm?

**Comment by drinfernoo** [comment]
Actually, I'm not sure. I haven't played Animania on 1.10.2, so I might should've kept my mouth shut for now.
