### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by KhaosKrew-Kirito** [setycz/ChickensMod#92]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

#### Steps to reproduce (important):

1. 
2. 
3. 
...

#### What you expected to happen:

____
#### Affected Versions (Do *not* use "latest"):

- Chickens: 
- Minecraft: 
- Forge:

**Comment by GenDeathrow** [comment]
This is an issue tracker not a forum. if you have a bug report it.
