### ISSUE TITLE
[1.11.2] Ticking Entity Crash after going back into world.

### ISSUE THREAD

**Issue by brisingraerowing** [setycz/ChickensMod#93]
#### Issue Description:
Went into a world to start playing, and after about 2-3 minutes a Ticking Entity crash happened.

#### Steps to reproduce (important):

1. Go into a world
2. Leave
3. Go back in
4. Wait.
5. Crash

#### What happens:
Ticking entity crash

#### What you expected to happen:
No crash

____
#### Affected Versions (Do *not* use "latest"):

- Chickens: 5.0.0
- Minecraft: 1.11.2
- Forge: 13.20.1.2425

[Crash Log](https://gist.github.com/BrisingrAerowing/b29afe9d01a835fbfa5df44ab6ebb9a0)

**Comment by GenDeathrow** [comment]
It seems to be crashing when it try's to lay an item. Basically the item is null or incorrect.  Do you also have More chickens installed? Id almost bet its more chickens and something has messed up with the configs(If you didn't edit it than I will need to double check everything). But none the less there needs to be a null pointer catch on the chickens mod so this doesn't happen again. give me a couple days.

**Comment by brisingraerowing** [comment]
I have more chickens, and I haven't edited the config.

**Comment by GenDeathrow** [comment]
In side your log folder there should be a chickens folder. See if the log shows any errors. Also delete the chickens config files and let them regenerate again. If we can figure out which chicken it is. I may be able to fix the issue.

**Comment by GenDeathrow** [comment]
There still needs to be a error catch anyways for a missing item or for something like this.

**Comment by drakray** [comment]
is there an ETA for this fix? I REALLY love Chickens and More Chickens, but as of now I CTD every 10 minutes T_T

**Comment by GenDeathrow** [comment]
Was suppose to get it out this last week, I have to double check something. and will try to get it out soon. but no exact date.

**Comment by GenDeathrow** [comment]
Hopefully v5.0.1 should fix this issue.

**Comment by drakray** [comment]
Seems to work perfectly :D

**Comment by GenDeathrow** [comment]
Good Im glad, this bug was a big one.. that needed to be squash. Thank you for taking the time to replay.
