### ISSUE TITLE
Certain chickens not wanting to breed with certain others. Racist chickens?

### ISSUE THREAD

**Issue by Twisted-Code** [setycz/ChickensMod#97]
#### Issue Description:
Some chickens will not, when put into breeding mode, seek out certain other chickens. essentially, chickens being racist, I guess? this happens on a SpongeForge server using a custom mod pack I made.

#### Steps to reproduce (important):
  
no freaking clue  how to reproduce it, but if you tell me how, I can try and get you the NBT tags of all the chickens I'm currently working with
1. 
2. 
3. 
...

#### What happens:
to explain more clearly than the above description, an example might be best. Suppose I have chickens A, B, C, and D.  Chicken A B and C will not breed with each other for some reason, no matter how many times I try giving them seeds. Instead, they wait until I give seeds to chicken D, at which point all three of them start group-raping D.
also, this seems to have nothing to do with what type of chickens are involved.

#### What you expected to happen:
all chickens to be willing to breed with any other chicken, like vanilla chickens are. Vanilla chickens breed  regardless of race, gender, and the scientific impossibility of M/M and F/F fertility

____
#### Affected Versions (Do *not* use "latest"):

- Chickens: chickens-4.3.2
- Minecraft: 1.10.2
- Forge: forge-1.10.2-12.18.3.2477-universal
Also, in case these versions are relevant:
- spongeForge: spongeforge-1.10.2-2477-5.2.0-BETA-2637
- MoreChickens: MoreChickens-1.10.2-1.1.6

**Comment by brisingraerowing** [comment]
There is a custom breeding system in place for the creation of various chickens. You can use JEI to view what chickens can breed and what kind of chicken they produce. Ex. Breeding a Coal Chicken with a Quartz Chicken will (possibly) produce a Lava Chicken.

**Comment by GenDeathrow** [comment]
@macks2008 Strange, tbh they use the normal vanilla mechanic for breeding. So it should work unless something is changing it.

**Comment by GenDeathrow** [comment]
I couldn't ever reproduce this so closing for now
