### ISSUE TITLE
[1.12.2] Server Crash

### ISSUE THREAD

**Issue by BuilderDan** [setycz/ChickensMod#98]
#### Issue Description:
Note: Server crashes on startup with mod.

Crash: https://pastebin.com/x08dAFTp

#### Steps to reproduce (important):

1.  Put into server
2.  Load server
3.  Watch it not load and crash
...

#### What happens:
Crashes Server

#### What you expected to happen:
For it to work

____
#### Affected Versions (Do *not* use "latest"):

- Chickens: Chickens 6.0.0v (MC 1.12.2)
- Minecraft: 1.12.2
- Forge:  forge-1.12.2-14.23.0.2544-universal.jar

**Comment by GenDeathrow** [comment]
Yup... looks like forge, added a new client side only metod. Sorry this didn't show up when testing.

**Comment by GenDeathrow** [comment]
Fixed on version 6.0.2
